### ISSUE TITLE
Decide on order of Sidebar Icons

### ISSUE THREAD

**Issue by funkatron** [spazproject/Spaz-Enyo#100]

**Comment by willhoney7** [comment]
I swapped assignment since nick has some other stuff to do :)

**Comment by funkatron** [comment]
Go for it!

## 

Ed Finkler
http://funkatron.com
@funkatron
AIM: funka7ron / ICQ: 3922133 / XMPP:funkatron@gmail.com

**Comment by willhoney7** [comment]
What if we swap around the sidebar? I was thinking a good about icon would be the spaz icon itself, but that would work best at top. So perhaps:

About
Prefs
Accounts
Columns
--spacer--
Refresh
Search
Post

Thoughts?

Honestly, we need devices to know what area is more natural to hit since they will obviously use composing, searching, and refresh most often.

**Comment by funkatron** [comment]
You should talk to dcousineau about this, since he will be going to Sunnyvale in a day or so to test on devices

## 

Ed Finkler
http://funkatron.com
@funkatron
AIM: funka7ron / ICQ: 3922133 / XMPP:funkatron@gmail.com

**Comment by dcousineau** [comment]
NOTED

**Comment by nguarracino** [comment]
I think you're right about needing to test on devices, but I would guess we don't need About in the sidebar. I think the app menu would be fine.

**Comment by willhoney7** [comment]
We need an about in the sidebar for non-webOS environments though..

**Comment by funkatron** [comment]
Agreed; that may be something we can do in the next milestone tho. Also, those other envs will have menus a-la the App menu in webOS.

## 

Ed Finkler
http://funkatron.com
@funkatron
AIM: funka7ron / ICQ: 3922133 / XMPP:funkatron@gmail.com

**Comment by willhoney7** [comment]
I'm going to rename this issue, since the about popup itself is done, but we don't know on the order of sidebar items.

**Comment by funkatron** [comment]
I think daniel said the new re-order makes more sense. I suspect it does because the most common actions are now closer to the left thumb of the touchpad user.

We might think about spacing the icons a little more; I think they look a bit shoved together. Otherwise I think this is a go.

**Comment by willhoney7** [comment]
I agree, they do look a bit shoved together. Lemme see what I can do.

**Comment by dcousineau** [comment]
The UX guy said they typically go for 54px square but in my playing with it we can get by with skinnier. What we had wasn't terrible, spacing would help.

**Comment by willhoney7** [comment]
Yeah. The toolbars are by default 54px but we decided to change them, to save space.

**Comment by funkatron** [comment]
I call it "decided"
