### ISSUE TITLE
Add Delete Entry to EntryView

### ISSUE THREAD

**Issue by funkatron** [spazproject/Spaz-Enyo#101]
Totally forgot about this: users need to be able to delete entries. These include:
- entries they've posted
- private messages they've posted OR private messages they've received

Checking account username+tyep vs entry author+service should tell you if a public entry can be deleted.

On deletion, it should be removed from any columns that contain it.

Will, if you add an icon, that would be awesome. I can probably do the rest.

**Comment by nguarracino** [comment]
This commit adds deleting of entries and messages when tapped in a column. Some major things still remaining:
- We need to fill out entry.is_author and entry.is_private_message when appropriate. Right now that's only being done in columns, not user/conversation view.
- We need an icon - the two that come to mind are already being used for block user, and as the close icon.
- We should probably confirm deletion of the entry.

**Comment by willhoney7** [comment]
An eraser could work as an icon, if we can find/make one.

**Comment by funkatron** [comment]
Okay, so:
- Conversations and User views will never have entry.is_private_message === true, because they don't show priv messages
- I've updated setAdditionalEntryProperties so it's not specific to Columns anymore. It's under AppUtils now.
- Can you get in a prompt for deletion, nick? Just follow the example of the confirmPopup in Container.js

**Comment by funkatron** [comment]
So is this good now?

**Comment by nguarracino** [comment]
## Yup, I think we're all set.-- Sent from my Palm Pre 2 running webOSOn Jun 13, 2011 0:04, funkatron reply@reply.github.com wrote: So is this good now?
