### ISSUE TITLE
Swiping away while keyboard open focused in compose popup locks application

### ISSUE THREAD

**Issue by dcousineau** [spazproject/Spaz-Enyo#103]
I have no clue if this is a Palm thing (probably is, they've been informed) but logging it here.

When you open teh compose popup and the txtbox is focused with teh keyboard open, and you swipe away to cardview, when you return everything is locked. This doesn't happen in StyleMatters so who knows.

**Comment by dcousineau** [comment]
Possibly solved by the performance issues, will need Ed or someone else to reconfirm when we can get a newer build up and running.

**Comment by nguarracino** [comment]
@funkatron Have you ever seen this on your TouchPad?

**Comment by dcousineau** [comment]
## I noticed this @ palm and showed a all the engineers I could...-- Sent from my Franken Pre 2On Jun 16, 2011 6:56 PM, nguarracino reply@reply.github.com wrote: @funkatron Have you ever seen this on your TouchPad?

**Comment by funkatron** [comment]
AND DID THEY FUCKING FIX IT????!?!?!?!

**Comment by funkatron** [comment]
so seriously, did they fix this?

**Comment by nguarracino** [comment]
## I've never seen it on my TouchPad.-- Sent from my HP TouchPadOn Jul 14, 2011 19:23, funkatron reply@reply.github.com wrote: so seriously, did they fix this?

**Comment by funkatron** [comment]
Closing!
