### ISSUE TITLE
Give background color to whole document

### ISSUE THREAD

**Issue by dcousineau** [spazproject/Spaz-Enyo#104]
When you open detail view with little content, you'll see the about content in index.html leaking through (As there is no background set). This is fixed when using sliding panes, however even when doing those you still see the palm grey for a little bit. We need to apply our dark grey background to the document entirely.

**Comment by willhoney7** [comment]
I noticed this, it should be easy enough. Fixing now.

**Comment by willhoney7** [comment]
oh. @nguarracino might have fixed this by adding "display: none" to the div in index.html..

Lemme know if you ever see it since that commit.

**Comment by funkatron** [comment]
this looks done.
