### ISSUE TITLE
Reduce the number of components in the entry

### ISSUE THREAD

**Issue by dcousineau** [spazproject/Spaz-Enyo#107]
WAaaay too many, major issues performance wise.

allowHtml: true, layout that way.

**Comment by dcousineau** [comment]
Column.js line 342: DON'T READ THE DOM

**Comment by willhoney7** [comment]
Okay, did this.

Also, the forced column resizing was a result of me having issues getting the scroller to flex naturally in the very beginning. I had to rig a set height.. but it looks like you fixed it :)

**Comment by dcousineau** [comment]
Well, still working on it. Going to redo what I started @ palm hq, will have a pull request by Sunday (long day today and tomorrow)

**Comment by willhoney7** [comment]
Sure, no worries. Runs a lot smoother in browser too.

**Comment by funkatron** [comment]
It looks like we lost the reposter avatar when we switched to HTML for the body of the entry

**Comment by willhoney7** [comment]
Oh we did. Lemme fix that.

**Comment by willhoney7** [comment]
Fixed in 95027dc9703404909841

**Comment by willhoney7** [comment]
Closing. Can re-open if we need..
