### ISSUE TITLE
Reposter avatar being shown incorrectly

### ISSUE THREAD

**Issue by funkatron** [spazproject/Spaz-Enyo#110]
I am betting the value is not being unset/cleared out correctly when the next entry is rendered.

![](https://img.skitch.com/20110612-m4xt4bdnq6unped5c2nr41gbfq.png)

**Comment by nguarracino** [comment]
I think this should do it. Please let me know if you are still seeing the reposter avatar after this change.

**Comment by willhoney7** [comment]
Not seeing it here anymore. Nice job!

**Comment by funkatron** [comment]
So we good? closing.
