### ISSUE TITLE
Indicate that we are getting a request token during Twitter auth flow

### ISSUE THREAD

**Issue by funkatron** [spazproject/Spaz-Enyo#119]
We need to indicate that we're getting a request token during that first step of the auth flow. If it is slow, it appears as if the app just isn't doing anything. People will start mashing buttons then.

**Comment by funkatron** [comment]
Nothing changed in the auth flow. inability to validate would be something else, but I've not had issues. Note that it is sensitive to the time being incorrect.

## 

Ed Finkler
http://funkatron.com
@funkatron
AIM: funka7ron / ICQ: 3922133 / XMPP:funkatron@gmail.com

**Comment by jaf0** [comment]
On 06/20/2011 09:13 AM, funkatron wrote:

> Nothing changed in the auth flow. inability to validate would be something else, but I've not had issues. Note that it is sensitive to the time being incorrect.
> 
> ## 
> 
> Ed Finkler
> http://funkatron.com
> @funkatron
> AIM: funka7ron / ICQ: 3922133 / XMPP:funkatron@gmail.com
> 
> On Monday, June 20, 2011 at 12:11 PM, jaf0 wrote:
> 
> > On 06/19/2011 10:47 AM, funkatron wrote:
> > 
> > > We need to indicate that we're getting a request token during that first step of the auth flow. If it is slow, it appears as if the app just isn't doing anything. People will start mashing buttons then.
> > > not sure if i didn't pull the most recent commit, but I was unable to
> > > validate the oauth token with spaz HD.... on device.
> > 
> > ## 

How sensitive (+/-)?

**Comment by funkatron** [comment]
I dunno exactly, but it's 15min max.

Anyway, point is – if you found a bug in our code, I need way more info (exactly details of HTTP traffic, etc). But it's probably not a bug in our code.

## 

Ed Finkler
http://funkatron.com
@funkatron
AIM: funka7ron / ICQ: 3922133 / XMPP:funkatron@gmail.com
