### ISSUE TITLE
Unread count not being displayed for newly created accounts

### ISSUE THREAD

**Issue by nguarracino** [spazproject/Spaz-Enyo#122]
I think it's because the last read date for new columns is 1. In Column.markOlderAsRead() we only call Column.countUnread() if there are entries older than the last read date, but nothing is older than 1. I think we should be able to call Column.countUnread() from Column.create().

**Comment by funkatron** [comment]
good catch!

**Comment by nguarracino** [comment]
This change works, but there may be a better way to accomplish it. Like maybe if we choose a different default value for lastRead, we wouldn't have to have a special case to force counting unread entries.
