### ISSUE TITLE
Pull to Refresh

### ISSUE THREAD

**Issue by willhoney7** [spazproject/Spaz-Enyo#125]
Since we will be removing the bottom toolbar, we need a way for users to refresh their columns. Pull to refresh would work well.

Here is an example for mojo: https://github.com/Tibfib/Pull-To-Refresh-for-HP-webOS

I have no idea if the events are the same in enyo, but it may be helpful.

**Comment by funkatron** [comment]
I gave this to eberon so he would be forced to work on it

**Comment by willhoney7** [comment]
Closing, awesome job @eberon and @funkatron!
