### ISSUE TITLE
Drag and Drop Columns

### ISSUE THREAD

**Issue by willhoney7** [spazproject/Spaz-Enyo#126]

**Comment by willhoney7** [comment]
Okay. I went out on a limb here and decided to work on live column re-ordering by holding onto the toolbar and dragging around the column.

The performance will have to be tested by @funkatron with his magical device. I think this will be easier than moving the column popup into a management one.

Thoughts?

**Comment by willhoney7** [comment]
OH. I should add. An issue we are going to have is that when dragging a column the scroller does not scrolll. We are going to have to fake a scroll when the mouse hovers around the edges.

**Comment by funkatron** [comment]
FYI, the tap/hold to drag seems to be working well on the device.

**Comment by willhoney7** [comment]
I'm going to call this done. There are a couple bugs, and I'll make issues for them.
