### ISSUE TITLE
Need to denote entries from private users in UI

### ISSUE THREAD

**Issue by funkatron** [spazproject/Spaz-Enyo#129]
I realized that we don't have anything that indicates a post comes from a private twitter/statusnet user. I think the little padlock icon works well. Need to show in column entries, EntryView, and UserView (privacy is user-level, not entry-level)

**Comment by willhoney7** [comment]
@funkatron What is the entry property to see if it is private?

**Comment by willhoney7** [comment]
Okay, this is done for ui.

I'll let @funkatron make a new icon and/or close this.

**Comment by funkatron** [comment]
look good. closing!
