### ISSUE TITLE
Re-creating columns after dropping a column has issues.

### ISSUE THREAD

**Issue by willhoney7** [spazproject/Spaz-Enyo#132]
this.createColumns() on the spacerDrop function creates issues with starting a column drag. To replicate: Hold onto a column toolbar, move it slightly, release. It will float in an awkward postion. this doesn't happen if this.createColumns() is commented out.

**Comment by funkatron** [comment]
Has this been fixed?

**Comment by nguarracino** [comment]
Not sure, I tried the steps that Will described a few times and it seemed to
be ok. The UI can lock up while the columns are being regenerated though.
This was on the 3.0.2rc1 SDK.

**Comment by funkatron** [comment]
ah yes -- this is still an issue. I think tibfib and I talked about a possible solution (checking to see if the column state is still "dragging" after a few seconds of non-movement).

With regeneration lockup, can you explain how that can be replicated?

**Comment by nguarracino** [comment]
I just followed the steps here - basically, pick up a column and drop it
again. It's not a permanent lockup, but the UI is unresponsive while the
columns are destroyed and recreated.

**Comment by funkatron** [comment]
ah right. that's gonna be an issue… I think it's just a performance thing. The caching I did prob helps a bit, but we should look for more places we can cache stuff and not have to do tasks more than once, especially anything related to dom manipulation – that kills perf.

## 

Ed Finkler
http://funkatron.com
@funkatron
AIM: funka7ron / ICQ: 3922133 / XMPP:funkatron@gmail.com
