### ISSUE TITLE
Add text, url shortening to posting

### ISSUE THREAD

**Issue by funkatron** [spazproject/Spaz-Enyo#14]

**Comment by jaf0** [comment]
also, custom bit.ly shortening via API...

**Comment by funkatron** [comment]
## That's something to wait for another milestone - no time for this one.Ed Finkler@funkatronFunkatron.comSent from my Palm PreOn May 8, 2011 1:58 AM, jaf0 reply@reply.github.com wrote: also, custom bit.ly shortening via API...

Reply to this email directly or view it on GitHub:
https://github.com/funkatron/Spaz-Enyo/issues/14#comment_1118438

**Comment by willhoney7** [comment]
I'm gonna close this one and add another for other url shortening.
