### ISSUE TITLE
Better column management

### ISSUE THREAD

**Issue by funkatron** [spazproject/Spaz-Enyo#140]
Right now, we have drag and drop columns in master, thanks to Tibfib. There is a big of bugginess with it, but I think these things are solvable. Going with this will allow us to drop the footer on the columns entirely, which is pretty cool.

**Comment by willhoney7** [comment]
So are we going to keep the drag and drop columns? Or should I work on improving the columnsPopup?

Thoughts everyone?

**Comment by funkatron** [comment]
so, for now, I'm going to call this "adequate." We should keep revisiting this, though.
