### ISSUE TITLE
Private Twitter lists don't show up in dropdown

### ISSUE THREAD

**Issue by funkatron** [spazproject/Spaz-Enyo#148]
From user: "The two lists that do show seem to be public lists, the other lists are private. FYI: I am able to see private lists in Socialite."

**Comment by eberon** [comment]
I'll get on it. I created my first private list and I can confirm that the API URL in use in Spazcore isn't doing the trick, so some obnoxious digging in Twitter API docs is needed.

**Comment by funkatron** [comment]
Maybe the SpazTwit object just needs authentication?

## 

Ed Finkler
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
