### ISSUE TITLE
support replying to a message

### ISSUE THREAD

**Issue by funkatron** [spazproject/Spaz-Enyo#16]
Note that which account we are replying from may be limited based on the service. A message we are replying to may not be from the service we last posted from! Options for which account to post from need to be limited by service.

**Comment by paddycarver** [comment]
Wishlist: Offer the ability to change what account in a service is replying. Sometimes I want to reply from an account that is different from the one mentioned.

**Comment by funkatron** [comment]
Yes, I think that is doable. We would be able to pick from the set of accounts that match the service we're replying on.

**Comment by willhoney7** [comment]
When you pass an entry to the reply popup, it should look at the service it is from and from there build the account toggle buttons. I think that will be the best experience.

That will probably be something we want to include in the "universal entry object" (converted tweets, identi.ca posts, etc.): what service it is coming from.

**Comment by funkatron** [comment]
Basics for replying to an item in a column is working. Still need to:
- reply to a dm
- reply from EntryView
- show the in_reply_to entry text
- pass the in_reply_to id
