### ISSUE TITLE
Delay initial rendering until preferences load

### ISSUE THREAD

**Issue by funkatron** [spazproject/Spaz-Enyo#18]
We need to not render anything until the preferences load. How to we delay this?

**Comment by dcousineau** [comment]
In the `create` method for the `Spaz` kind, anything that blocks the `self.inherited(arguments);` blocks rendering, once `SpazPrefs.load()` gets fleshed out, `initAppObject()` could pass in a callback with some kind of failover?

**Comment by funkatron** [comment]
Yeah, you could pass the callback and make sure it goes into the callback for prefs.load(). Wanna try that?

**Comment by dcousineau** [comment]
I can toss something together and just have SpazPrefs.load just trigger a callback since it's a stub anyways

**Comment by dcousineau** [comment]
Yeah, I'll add success and fail callbacks to SpazPrefs.load later tonight, I experimented and got it to completely block loading of Spaz until prefs were loaded.

**Comment by funkatron** [comment]
Perfect, thanks. Also need to think about how we're storing prefs (thinking Lawnchair using webSQL) but that's another issue

**Comment by willhoney7** [comment]
We should be able to do this stuff in index.html before calling "new Spaz().renderInto(document.body);"

**Comment by funkatron** [comment]
I think it would be better to keep it within the Spaz kind code if possible.

**Comment by willhoney7** [comment]
Sure. We will have to do the multi-stage stuff in the index.html, so it may be better to separate too.

**Comment by dcousineau** [comment]
080633587c5780230603a71202a71b280243135c should take care of this quite nicely for now.
