### ISSUE TITLE
decide on initial services targets

### ISSUE THREAD

**Issue by funkatron** [spazproject/Spaz-Enyo#19]
My thinking is that we shoot for what we do now:
- Twitter
- Identi.ca
- StatusNet/Custom Twitter-compatible API

**Comment by paddycarver** [comment]
I'd like to see Buzz and Facebook in the future, but that's a bit down the road, as far as I'm concerned.

**Comment by funkatron** [comment]
yeah, that would be nice. maybe file an issue on that in the "Future" milestone.

**Comment by willhoney7** [comment]
I think Twitter, Identi.ca, and StatusNet for initial release is good. And probably not do a lot of service specific stuff (like Twitter lists and Ident.ica groups). Then after release we can dedicate specific updates to specific services.

EDIT: woops, accidentally closed it too.

**Comment by funkatron** [comment]
I'd say Twitter, Identi.ca, and StatusNet/Custom systems are the target. Done.
