### ISSUE TITLE
Decide on column types supported

### ISSUE THREAD

**Issue by funkatron** [spazproject/Spaz-Enyo#20]
I think we should support the subset of column types shared by our initial services. I'd think these are:
- Home timeline
- Replies/Mentions
- DMs
- Searches

If time allows, I would also include
- Unified (Home + Mentions + DMs)

**Comment by willhoney7** [comment]
I think unified should come as soon as possible. It is spaz's "trademark" feature.

I would like search columns to be built flexibly to allow users to put more than one search term in a column.

We also need to decide whether we are going to have columns for data that people only care about temporarily. Like when I do a search, 90% of the time I just want to look at it once and don't want a new column. I was thinking earlier that the search results from a search by tapping the sidebar button could be shown in a popup with options to save the search as a column. And of course, if a user goes through the new column popup, the search will be saved as a column. 

So if we follow that model, there would probably not be a column for your followers/following or others' (it would just be an area in the profile view). Although, a new followers column may be appreciated by some users..

I think twitter trends should be a column, and we could also look at having a sidebar button that shows a popup of them. 

Of course those columns aren't targeted for the initial release, but I think we need to decide now how the columns are going to be used now.

**Comment by funkatron** [comment]
Yes, I would really like to get unified in the initial release, if at all possible. I want to do it right, though, and with a model different than the Mojo version. I want it to support paging back in this approach.

I like your idea of initially showing in a popup, and saving as a column if desired. Maybe not for initial release, or as a "nice to have" but not killer if we don't have it.

I think I'd like to have just one search per column, but a user could click on the title of the column and change the search that way. What do you think? I'm leery of multiple searches per column; it means juggling more data and will eat through API limits faster, and I don't think it's a feature most people will use. you can accomplish most of it by just using search operators, too (like "metal OR rock").

I'm mixed on Trends, but it's fine to do I think for down the road.

friends and followers is probably good for the profile, like you say. we'll think some about it.

**Comment by willhoney7** [comment]
Oh wow, I completely forgot about search operators. There is definitely no need for supporting more than one search.

Yeah, we can wait for showing results in a popup, but I may add it sooner rather than later because adding a column every time is going to annoy me hah.

**Comment by funkatron** [comment]
I think we pretty much did this
