### ISSUE TITLE
Message Detail: View Conversation

### ISSUE THREAD

**Issue by funkatron** [spazproject/Spaz-Enyo#28]
Do that.

**Comment by funkatron** [comment]
See how we do this in spaz-webos, basically, and copy it.

**Comment by dcousineau** [comment]
Have some work done on my branch https://github.com/dcousineau/Spaz-Enyo/tree/conversation

How do we want to trigger? Figured we'd use a DividerDrawer (that's what I'm using right now).

**Comment by funkatron** [comment]
I think this is fine for now; maybe Tibfib might want to take a different UI approach, but the fact that it _works_ is great. I'm cool with you merging this in.

## 

Ed Finkler
http://funkatron.com
@funkatron
AIM: funka7ron / ICQ: 3922133 / XMPP:funkatron@gmail.com

**Comment by willhoney7** [comment]
I changed it to a button just to try it out. We can go back easily, just wanted to try it out and get feedback. Thoughts?

**Comment by willhoney7** [comment]
I'm going to close this. Good job @dcousineau!

Anyone: feel free to re-open this if we need to change the ui.
