### ISSUE TITLE
Preferences

### ISSUE THREAD

**Issue by willhoney7** [spazproject/Spaz-Enyo#35]
"Enter Posts": true
"Default Column Width": "322px"

Add any preferences here that should be incorporated.

**Comment by nguarracino** [comment]
URL shortening service.

**Comment by funkatron** [comment]
Here are things I'd like to see in the first milestone:
- network-refreshinterval
- network-searchrefreshinterval
- notify-new-entries
- notify-mentions
- notify-private-messages
- notify-search-results

**Comment by jaf0** [comment]
custom bit.ly URL?

**Comment by willhoney7** [comment]
Hey @clayhinson, any updates on this?

**Comment by willhoney7** [comment]
The ui to do this is there. Just needs to be hooked in by someone.

**Comment by funkatron** [comment]
Clay, do you want to work with me on this sometime soon? We can set up some time on skype if you like.

**Comment by clayhinson** [comment]
Yes! I'm free Tuesday evening after 8:30pm EST or so, and Saturday as well. I could make time other nights if need be.

**Comment by funkatron** [comment]
How's this going? we should submit something within 7 days. Need to know what can go in and what can't.

**Comment by willhoney7** [comment]
Okay, I've talked to clay and he's pretty busy so I've started work. 0b2039df2dfa3968b2e0 added basic setting. The preferences are not used anywhere.

@funkatron: I'm not sure what url shorteners are supported, can you update the settingsPopup with the choices?

**Comment by funkatron** [comment]
Thanks for checking.

We can get the supported URL shorteners with SpazShortURL.getServiceLabels(). Something like:

var shurl = new SpazShortURL();
var shurl_labels = shurl.getServiceLabels();

## 

Ed Finkler
http://funkatron.com
@funkatron
AIM: funka7ron / ICQ: 3922133 / XMPP:funkatron@gmail.com

**Comment by willhoney7** [comment]
So is searchrefreshinterval different? Do I need to hook that in now?

Oh, and thanks for the shurl stuff!

**Comment by funkatron** [comment]
## Not now, no. Ed Finkler@funkatronFunkatron.comSent from my Palm PreOn Jun 8, 2011 9:14 PM, Tibfib reply@reply.github.com wrote: So is searchrefreshinterval different? Do I need to hook that in now?

Reply to this email directly or view it on GitHub:
https://github.com/funkatron/Spaz-Enyo/issues/35#comment_1331278

**Comment by willhoney7** [comment]
Alrighty! Looks like this is closed!
