### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by willhoney7** [spazproject/Spaz-Enyo#37]
We need a new preferences icon. The current one looks crappy. A gear would probably be best.

**Comment by funkatron** [comment]
Tons of icons in the dropbox shared folder

**Comment by willhoney7** [comment]
Ooops! I looked before and all I could find was the slider thing we have now. Just noticed the gear!

I'm going to close this for now, and re open it if/when we need more icons.

**Comment by jaf0** [comment]
## Isn't there a stock prefs icon?Sent from my Palm PreOn May 11, 2011 6:21 PM, Tibfib reply@reply.github.com wrote: We need a new preferences icon. The current one looks crappy. A gear would probably be best.

Reply to this email directly or view it on GitHub:
https://github.com/funkatron/Spaz-Enyo/issues/37
