### ISSUE TITLE
Need to truncate "header"

### ISSUE THREAD

**Issue by willhoney7** [spazproject/Spaz-Enyo#39]
Since it uses "flex" there is no set width making our "truncating-text" class not work. 

We could probably do something by getting the width of the account label and subtracting that from a width and then hard-coding it in on create.

**Comment by dcousineau** [comment]
Committed a fix. In order for CSS truncation to work on flex-width elements, one must set `overflow:hidden;` as well as `white-space: nowrap;` which effectively makes it single line, so as long as truncating-text is only used on single line entities (like headings) we're fine.
