### ISSUE TITLE
Support API RTing a message

### ISSUE THREAD

**Issue by funkatron** [spazproject/Spaz-Enyo#41]
API RT

**Comment by paddycarver** [comment]
Considering I wrote that API in SpazCore, this feels like a project for me...

**Comment by funkatron** [comment]
Absolutely!

## 

Ed Finkler
http://funkatron.com
@funkatron
AIM: funka7ron / ICQ: 3922133 / XMPP:funkatron@gmail.com

**Comment by paddycarver** [comment]
Stupid question, I'm sure. Where are the custom methods (this.doReply, this.doDirectMessage, etc.) being called in EntryClickPopup.js being defined? I did a grep search, and couldn't find any definition for them.. Am I missing something obvious?

**Comment by funkatron** [comment]
implemented in 4cc271976e394fc6db63f36e4315471c5583708f
