### ISSUE TITLE
Support "manual" RTing a message (RT @xxx …)

### ISSUE THREAD

**Issue by funkatron** [spazproject/Spaz-Enyo#42]
^^^

**Comment by paddycarver** [comment]
Will try my hand at this when I'm doing the manual retweets. I'm thinking the TweetDeck style interface-- Tweet box is populated, if not edited, it's a native retweet. If edited, a fake retweet. Objections?

**Comment by funkatron** [comment]
I prefer offering two diff options for the user. in Spaz webOS, we offer under Sharing…
- Retweet
- RT @…
- /via @…

So the first is an API RT, and it's totally in the bg. The other two would open the compose popup and prepopulate it.

## 

Ed Finkler
http://funkatron.com
@funkatron
AIM: funka7ron / ICQ: 3922133 / XMPP:funkatron@gmail.com

**Comment by paddycarver** [comment]
Alright, will do. Is this ticket covering UI, wiring, backend, or all three?

**Comment by funkatron** [comment]
implemented in 4cc271976e394fc6db63f36e4315471c5583708f
