### ISSUE TITLE
Display Twitter API RTs correctly

### ISSUE THREAD

**Issue by funkatron** [spazproject/Spaz-Enyo#45]
Twitter API RTs are funky in that they have a whole separate status object just for the _full_ retweeted message. If you don't use that, you can lose some chars due to the 140char limit imposed. So, we need to do a little work to display them correctly.

**Comment by paddycarver** [comment]
Shall I just take on the mantle of Lord of the Retweets? As long as I'm tackling them, I may as well tackle them completely...

**Comment by funkatron** [comment]
Do it to it, dude!

## 

Ed Finkler
http://funkatron.com
@funkatron
AIM: funka7ron / ICQ: 3922133 / XMPP:funkatron@gmail.com

**Comment by funkatron** [comment]
Actually, thinking more about it, this should be mostly an issue of having AppUtils.convertToEntry() to handle the API RT situation and properly convert it, adding a new properly called "is_repost" and perhaps "repost_user" or something like that.

**Comment by willhoney7** [comment]
@funkatron, that would make it super easy for paddyforan or myself to plug into Entry.js.

I think we should folow the styling of the Mojo, with the original username, a retweet icon, and then the retweeter.

**Comment by funkatron** [comment]
I think I've provided all the appropriate data in the Entry object now. See 1cfdbeae37bc3313733caca582812a65c2282f10

**Comment by willhoney7** [comment]
Awesome, I'll hook this in shortly.

**Comment by willhoney7** [comment]
I think we can consider this done!
