### ISSUE TITLE
Disable controls and show spinner when posting

### ISSUE THREAD

**Issue by funkatron** [spazproject/Spaz-Enyo#47]
When we send, we need to:
- Disable compose/post controls
- show some sort of spinner
- be able to display an error and de-enable controls

**Comment by nguarracino** [comment]
Any preference on how we should display an error? We could just show a banner, or we could do something more obtrusive like an error popup.

**Comment by funkatron** [comment]
I'm working up a simple notification lib that will help. coming very shortly.

**Comment by nguarracino** [comment]
Awesome, that looks great. I think this can be closed then.

**Comment by funkatron** [comment]
Can we disable all other controls as well? It looks like you can still edit the message while it sends, and _that_ can actually re-enable the send button. We should disable _all_ controls, except the close panel [x]

**Comment by nguarracino** [comment]
The change I just committed should do what we want, except that RichText.setDisabled(true) doesn't seem to work. I've posted a question on the forums to see if it's a bug.

**Comment by nguarracino** [comment]
I heard back on the forum and unfortunately, RichText controls cannot be disabled at the moment. This latest change attempts to work around that by throwing out any keydown events if the control is disabled. So you can still focus the control but you can't enter any characters so the Send button stays disabled.

**Comment by willhoney7** [comment]
We could have an "onFocus" listener that blurs focus. I'm going to play with it and see if that works better.

**Comment by willhoney7** [comment]
I just committed that change. Should work pretty well.
