### ISSUE TITLE
Color mentions and dms differently

### ISSUE THREAD

**Issue by funkatron** [spazproject/Spaz-Enyo#48]
We should differentiate mentions and dms somehow; perhaps with a colored gradient in the bg. Open to suggestions.

**Comment by paddycarver** [comment]
Thoughts on providing a setting for this? I'm flying blind after a week of not playing with the source (I'm a bad person, I know), but I'm pretty sure this would be easy enough to do, so I'd be willing to take it on. Just need to figure out exactly what it should be-- preference, hard-coded, etc.

**Comment by funkatron** [comment]
So my feeling is that we keep it simple for now and hard-code it into the theme – that's how we've generally approached it in previous versions. I was hoping Tibfib would take the lead here, since he's leading UI stuff. OH TIBFIB!

**Comment by willhoney7** [comment]
oh yeah, I can do this one. I'll do it now. 

I was also thinking about just hard-coding it into the theme.

**Comment by willhoney7** [comment]
This is done, UI wise. It just needs @funkatron or someone else to hook in an "is_mention" property for entries. see apputils.js

**Comment by funkatron** [comment]
Added is_mention in 2ffe264a20f52153d7934ccbcf2e403e6b75654e

**Comment by willhoney7** [comment]
Alrighty, closed!
