### ISSUE TITLE
Entry click popup can be drawn partially offscreen

### ISSUE THREAD

**Issue by nguarracino** [spazproject/Spaz-Enyo#49]
Popup.openAroundControl is smart enough to position your popup so it is completely onscreen, but Popup.openAtEvent is not. So if you tap on the right-most column, the items in the popup can be truncated or even completely obscured.

**Comment by funkatron** [comment]
what I'm seeing in Chrome is that the EntryViewClick is opening wayyyyy far to the left if the EntryView is near the right side of the window.

Video: http://screencast.com/t/u4RxT6UWuOqP

**Comment by nguarracino** [comment]
Damn, ok. I noticed it didn't always work right in the emulator either. I'm out right now but I will take a look once I'm home. If I can't get it working well I'll just revert it.

On May 14, 2011 19:25, funkatron &lt;reply@reply.github.com&gt; wrote: 

what I'm seeing in Chrome is that the EntryViewClick is opening wayyyyy far to the left if the EntryView is near the right side of the window.

Video: http://screencast.com/t/u4RxT6UWuOqP

## 

Reply to this email directly or view it on GitHub:

https://github.com/funkatron/Spaz-Enyo/issues/49#comment_1164067

**Comment by funkatron** [comment]
thanks, we'll sort it out!

## 

Ed Finkler
http://funkatron.com
@funkatron
AIM: funka7ron / ICQ: 3922133 / XMPP:funkatron@gmail.com

**Comment by nguarracino** [comment]
I changed it to use Popup.openNear(). Seems to work better, although there is still an area of the rightmost column that can cause the popup to get truncated.

**Comment by nguarracino** [comment]
I posted a question with some sample code on the forums, and Jeremy confirmed it is a bug that has been fixed with the latest SDK. Reopening this issue as a reminder to test once the new SDK is released.

**Comment by nguarracino** [comment]
This is working with Enyo 0.10.
