### ISSUE TITLE
Image Previews

### ISSUE THREAD

**Issue by willhoney7** [spazproject/Spaz-Enyo#53]
With the virtual lists' gradual loading of items, embedded previews could work pretty well.

**Comment by funkatron** [comment]
I can definitely set up something in the message detail like the Mojo version

**Comment by willhoney7** [comment]
@nguarracino incorporated this into EntryView.js. Now we need to add it to Entry.js itself and add options for users on Image Previews.

**Comment by nguarracino** [comment]
We should also look at the embedly work @funkatron has done which may make this a little easier.

**Comment by funkatron** [comment]
Yeah, look in the beta branch of the mojo version. it works, but some users preferred the in-app previews. I'd suggest looking for stuff as now, and if it does not find anything, then firing off the embedly stuff to pick up things we don't support in SpazImageURL

**Comment by funkatron** [comment]
Nick I'm assigning this to you, but feel free to ask any questions about the embed.ly stuff or whatnot.

**Comment by nguarracino** [comment]
Some sites are returning Flash previews, which doesn't seem to be working on the emulator. Here's an example:
http://explore.embed.ly/oembed/?mode=rich&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D7jCISIbs9_g

**Comment by funkatron** [comment]
Then we need to adjust the regex se we pass. Like I said, Flash isn't available in webOS apps.

## 

Ed Finkler
http://funkatron.com
@funkatron
AIM: funka7ron / ICQ: 3922133 / XMPP:funkatron@gmail.com

**Comment by funkatron** [comment]
I think we've gotten this working pretty well. Closing.
