### ISSUE TITLE
Git workflow (was "Hi Guys")

### ISSUE THREAD

**Issue by jaf0** [spazproject/Spaz-Enyo#55]
not sure if this is the best way to ask this, but ...

I'm fairly new to github. I have the general idea of the logistics behind RCS/CVS but...

I was wondering if ole' funkatron has some time next week (m-thur) sometime to actually face-to-face with me and spend a half hour going over what the "correct" way to do this would be....

(unless there's some quick and dirty  FAQ that would point me in the right direction.

Main Q's are as follows.

Should I work on my own fork and if so, how to integrate all that with what the rest of you are doing without conflicting yet being able to pull your goodies so I have a complete idea........
(ok. maybe I need a nuts-and-bolts quickie on this)

That's about it right now. Brain trying to hibernate.

TIA.

jaf0/Daniel

**Comment by dcousineau** [comment]
THERE CAN BE ONLY ONE DANIEL! We must now do battle like ye olde Highlanders.

Ed likes as much as possible done via forks and pull requests (one is reminded of [a specific shirt in his swag shop](http://spaz.spreadshirt.com/pull-request-or-stfu-black-A6928817/customize/color/2)). However, as this project is currently a private repo and undergoing rapid development, his standards have slacked temporarily.

Personally I always do my best to use forks and pull requests for new features (e.g. conversation detail) but tend to be lazy and commit bugfixes straight to trunk.

**Comment by thynctank** [comment]
Beat me to the punch. Hopefully I can actually contribute to this new project some before too long. Still haven't even seen it running on my own machine yet!

**Comment by jaf0** [comment]
@dcousineau ...

http://www.flickr.com/photos/beerorkid/2633180133/

http://failbook.failblog.org/2011/05/08/funny-facebook-fails-you-must-be-this-tall-to-die/

**Comment by funkatron** [comment]
I would prefer the following workflow:
1. Fork your own Github repo from mine.
2. Clone that repo (or add it as a new remote if you already have a repo)
3. work on your own local repo, branching for anything that's not a 1-2 line fix
4. push changes up to your Github repo
5. submit changes as a pull req to my repo

I didn't want to put a damper on anyone's enthusiasm, and having to work on a private repo makes this slightly more of a pain, so I haven't pushed hard on this. But it's definitely what I'd prefer, and I think it will result in a fewer merge problems.

**Comment by jaf0** [comment]
disregard previous (now deleted) post.

Use the source, Luke.

_hide_

**Comment by jaf0** [comment]
so how do I update my repo once you've pull'd? or does it automagically do it?

and how do I locally update my repo? 
git merge?

**Comment by dcousineau** [comment]
http://help.github.com/fork-a-repo/ is going to be your bible in this workflow.

A `git fetch upstream` followed by a `git merge upstream/master` will pull in the changes that have been made since and make sure you're in sync (you could shorten this process with a `git pull upstream master` which does a `fetch` followed by a `merge`). Then a `git push origin` will keep your fork on github up to date.

**Comment by jaf0** [comment]
On 05/16/2011 11:51 PM, dcousineau wrote:

> http://help.github.com/fork-a-repo/ is going to be your bible in this workflow.
> 
> A `git fetch upstream` followed by a `git merge upstream/master` will pull in the changes that have been made since and make sure you're in sync (you could shorten this process with a `git pull upstream master` which does a `fetch` followed by a `merge`). Then a `git push origin` will keep your fork on github up to date.
> 
> yeah, i already bookmarked that. :)

jaf0@hp-g61:~/git/Spaz-Enyo$ git fetch upstream
fatal: 'upstream' does not appear to be a git repository

(derp)
