### ISSUE TITLE
Account management icon is confusing

### ISSUE THREAD

**Issue by thynctank** [spazproject/Spaz-Enyo#56]
Maybe it's just me, but I feel like the account management icon shouldn't have the plus (maybe multiple little guy graphics or something instead?) because it's not just an "add account" feature.

**Comment by willhoney7** [comment]
I completely agree. I took a shortcut at the beginning since I didn't have a better icon at the moment. This should get fixed by first release.

**Comment by funkatron** [comment]
Any ideas on this? can we use something in our dropbox sets?

**Comment by funkatron** [comment]
Just changed the priority, but if we're gonna change this, needs to happen soon.
