### ISSUE TITLE
deleting account doesn't remove API key?

### ISSUE THREAD

**Issue by jaf0** [spazproject/Spaz-Enyo#58]
Apparently? when you remove an account, the API_KEY or some vestige of the account remains, because I re-added an account with a bad password to try to get an error, it's all good.... and the panels load with the information just fine? or is chrome caching something??

**Comment by funkatron** [comment]
could be a bug with actually removing the account from the model, or not saving on deletion. I'd step through it with the debugger in Chrome.

## 

Ed Finkler
http://funkatron.com
@funkatron
AIM: funka7ron / ICQ: 3922133 / XMPP:funkatron@gmail.com

**Comment by jaf0** [comment]
ok. cleared cache and restarted chrome. seems to work?

**Comment by funkatron** [comment]
Chrome can be overly aggressive about caching data. I would test it a few times to see if comes up again, though.

## 

Ed Finkler
http://funkatron.com
@funkatron
AIM: funka7ron / ICQ: 3922133 / XMPP:funkatron@gmail.com

**Comment by jaf0** [comment]
i did.
pushed a commit on the duplicate account issue.
submitted a pull request.

now if I could just remember all these steps later :)
