### ISSUE TITLE
is_own or something similar for entries.

### ISSUE THREAD

**Issue by willhoney7** [spazproject/Spaz-Enyo#65]
So we can visually distinguish them.

**Comment by willhoney7** [comment]
Also, for retweets, we need the the time of the original tweet.

**Comment by funkatron** [comment]
okay, I've added:

entry.repost_orig_date for reposts (retweets) 5d9ab81f4ef0147797112cdf5fbbcc1d9ce4198a
entry.is_author for messages posted by the retrieving account. this had to be added in Spaz.Column.processData() cf0c88915c9c9cc66447349c35f9ca125780c534
