### ISSUE TITLE
Incorporate Actions into EntryView

### ISSUE THREAD

**Issue by willhoney7** [spazproject/Spaz-Enyo#67]
Reply
Share
Handling clicking on tweets (conversation view) and usernames
Favorites(?)

**Comment by funkatron** [comment]
Giving this to Nick; can you close this out to add the repost stuff?

**Comment by willhoney7** [comment]
Share popup is the only thing left.

**Comment by funkatron** [comment]
## Kick assEd Finkler@funkatronFunkatron.comSent from my Palm PreOn Jun 1, 2011 5:37 PM, Tibfib reply@reply.github.com wrote: Share popup is the only thing left.

Reply to this email directly or view it on GitHub:
https://github.com/funkatron/Spaz-Enyo/issues/67#comment_1277343
