### ISSUE TITLE
UserView Actions

### ISSUE THREAD

**Issue by willhoney7** [spazproject/Spaz-Enyo#68]
Following
Block + Reporting (maybe for first release)
Send DM, Reply

and so forth.

**Comment by funkatron** [comment]
I'd like to see:
- Send msg (a mention)
- Send DM
- Follow/unfollow toggle (you have to do a network request to get the correct state, though. you can look at how Mojo does it)
- Block/Report

Basically follow what mojo does now. If you do up the UI I can wire up the stuff

**Comment by funkatron** [comment]
Most of these are working except for Follow/Unfollow atm.

**Comment by funkatron** [comment]
I believe this is now done as of 14d7353e7e6fd6c571216370fd98b68e1875477a
