### ISSUE TITLE
Non-repost entries shown as reposts

### ISSUE THREAD

**Issue by nguarracino** [spazproject/Spaz-Enyo#69]
I've seen a couple instances where my Home timeline shows a post as a repost when that person didn't actually repost it. Opening the post in the entry view correctly shows it's not a repost. Possible cause is that we are explicitly showing the RT stuff (icon, reposter name) if entry.is_repost is true. But we're not hiding it if it's false. Maybe the last entry that was rendered in that spot was an RT so we showed the RT elements and when the list was refreshed it was left showing.

**Comment by funkatron** [comment]
Would be awesome if you can include all screenshots/assets you have.

**Comment by nguarracino** [comment]
Sure - here is what it looked like in Chrome (the 2nd entry in the Home timeline should NOT be a repost) http://skitch.com/nguarracino/fynrj/spaz-rt

And here are the contents of the entry for the post in question: http://pastebin.com/e2Y2c2mB

**Comment by nguarracino** [comment]
I haven't seen this again after making this change.
