### ISSUE TITLE
Reposts near the top of the timeline are duplicated on refresh

### ISSUE THREAD

**Issue by nguarracino** [spazproject/Spaz-Enyo#70]
If a repost is in one of the first 3 (or so?) entries in my Home timeline, refreshing the timeline will duplicate the repost. It's not just a visual thing - I inspected the entries and the reposts are duplicated there as well. For some reason, reposts further down the timeline are not duplicated.

**Comment by funkatron** [comment]
This may be fixed as of fdfa223609e71ec0e65f75ec1f9593d815f1b995

**Comment by nguarracino** [comment]
Yup, haven't seen this since that change.
