### ISSUE TITLE
Reposts are sorted by original timestamp

### ISSUE THREAD

**Issue by nguarracino** [spazproject/Spaz-Enyo#71]
If someone has just reposted something from a few hours ago in Spaz Desktop, it shows up at the top of the timeline. However in Spaz HD that post would appear further down the timeline, sorted according to when the original post was made.

See this screenshot: https://skitch.com/nguarracino/fyrnu/rt-timestamp
(the missing icons are due to my stupid work VPN interfering with Twitter.)

**Comment by funkatron** [comment]
This should be fixed in fdfa223609e71ec0e65f75ec1f9593d815f1b995
