### ISSUE TITLE
Use oAuth PIN or callback flow for Twitter auth

### ISSUE THREAD

**Issue by funkatron** [spazproject/Spaz-Enyo#73]
xAuth will no longer allow us to access DMs as of June 30. We must change our authentication flow for Twitter.

I recommend for now using a PIN-based flow. If we can do an embedded web view and capture the data that's fine, but it seems a lot more fragile.

For now I'm giving this to Josh because he's working on getting full oauth flow into SpazCore. After that I can set up the guts and Will can do the UI.

Yep, it sucks, but Twitter is fucking us. It is what it is.

**Comment by funkatron** [comment]
assigning to tibfib for now since he can mockup the UI before he's off to the Old Country.

**Comment by willhoney7** [comment]
Okay, UI is done in branch pinAccount. Assigning back to Josh..

**Comment by funkatron** [comment]
Deadline has been pushed back to June 30. This should let us sort out the Enyo version and then have more time to work on Mojo/Desktop

**Comment by funkatron** [comment]
I have implemented this flow for Twitter on the pinAccount branch (as well as merging current master into pinAccount). It's not perfect, but it works. At this point I am not 100% sure we will be able to use the same consumer token; hoping for information on the dev list soon.

**Comment by funkatron** [comment]
For now I'm calling this closed. The stuff for Josh is really a spazcore issue, so it's independent of what we have working atm.

**Comment by funkatron** [comment]
Problem: the popup panel gets dismissed when we move to the browser card. GARRRRRRRRR.

Will inquire on form if this is something we can block. If not might need to make a webview appear or something.

**Comment by funkatron** [comment]
Okay, fixed popup being dismissed in 1c81eae8b60621c5c38826df8304c98c678da830
