### ISSUE TITLE
Update to Enyo 0.10

### ISSUE THREAD

**Issue by nguarracino** [spazproject/Spaz-Enyo#79]
This is going to require a bit of effort as 0.10 is not completely backward compatible with 0.9.

**Comment by willhoney7** [comment]
I just read through the changelog and it looks like we need to update VirtualRepeater's onGetItem to onSetupRow and need to update all the popups. 

All in all, I think  the update will help us out quite a bit. There is some stuff to force the keyboard open and close which we will probably want to do with the popups.

**Comment by funkatron** [comment]
Mostly a copy and paste job, then?

**Comment by funkatron** [comment]
err, search and replace even

**Comment by nguarracino** [comment]
For the VirtualRepeaters, yeah. The Popups may be a little more work. They use lazy initialization by default now so I think we'll have to add the onBeforeOpen event to set widget content, etc. If we run into problems, we could use lazy: false as a first step and then gradually switch over to lazy.

**Comment by nguarracino** [comment]
Here's another thing:

"An HTML content filter has been introduced into contentChanged in DomNodeBuilder; set allowHtml: true to defeat the filter. Note that you should not set the content property of a component directly. Doing so will bypass the HTML filter."

So it seems that any control where we would want to call setContent(makeItemsClickable()) is going to need allowHtml: true. Otherwise you will see raw <span> tags, etc. in the control. It looks like we could also change those controls to enyo.HtmlContent kinds.

**Comment by willhoney7** [comment]
Can someone push up Enyo .10 on a separate branch? Can't download it here.

**Comment by funkatron** [comment]
I don't have it yet (I'm at a conference with crappy wifi) but I think nguarracino was going to put it in the repo

**Comment by nguarracino** [comment]
Yeah I just wanted to check with @funkatron first about using the SDK version vs. the repo version.

I'm out at the moment but I'll check it in to the enyo-0.10 branch once I am back home.

On May 26, 2011 16:53, funkatron &lt;reply@reply.github.com&gt; wrote: 

I don't have it yet (I'm at a conference with crappy wifi) but I think nguarracino was going to put it in the repo

## 

Reply to this email directly or view it on GitHub:

https://github.com/funkatron/Spaz-Enyo/issues/79#comment_1245336

**Comment by funkatron** [comment]
Yeah, a big reason I want to keep publishing it is because I'm really hoping we can run this outside of webOS.

## 

Ed Finkler
http://funkatron.com
@funkatron
AIM: funka7ron / ICQ: 3922133 / XMPP:funkatron@gmail.com
