### ISSUE TITLE
Repost icon in EntryView

### ISSUE THREAD

**Issue by nguarracino** [spazproject/Spaz-Enyo#80]
Do we need one there? I think it makes sense.

**Comment by funkatron** [comment]
I think that is what the Forward/Share button is for. actually I think it would be appropriate to put Repost stuff under Share in the EntryClickPopup too. I just didn't.

## 

Ed Finkler
http://funkatron.com
@funkatron
AIM: funka7ron / ICQ: 3922133 / XMPP:funkatron@gmail.com

**Comment by nguarracino** [comment]
ok, that works. I thought that was just for sharing but as long as repost is accessible from EntryView in some way I'm happy.

**Comment by funkatron** [comment]
I basically consider Reposting to be Sharing, but on the same service. So that's my logic 8D
