### ISSUE TITLE
Should we add default columns whenever an account is created?

### ISSUE THREAD

**Issue by nguarracino** [spazproject/Spaz-Enyo#81]
Right now we only do it for the first account. I thought it would be good to create something (maybe just Home and Mentions) for subsequent accounts.

**Comment by willhoney7** [comment]
hmmm. I think for the first user we should create Home, Mentions, and Private Messages. 

I'm leaning towards no for creating columns for new accounts but I could be persuaded easily.

**Comment by funkatron** [comment]
Right now we don't populate any columns for first user (there's a set of default columns, but it's left over from initial mockups). We definitely need to do that. Additional users can wait for now, I'd say.

**Comment by funkatron** [comment]
My bad -- it does add the defaults on first account add. However, it probably should auto-open the accounts popup if no accounts have been created.

**Comment by nguarracino** [comment]
I updated it so whenever an account is added, Home, Mentions, and Messages columns will be created. We can tweak it some more if you guys would rather see something else.

**Comment by funkatron** [comment]
Good for now

## 

Ed Finkler
http://funkatron.com
@funkatron
AIM: funka7ron / ICQ: 3922133 / XMPP:funkatron@gmail.com

**Comment by funkatron** [comment]
marking as closed. we can revisit if needed.
