### ISSUE TITLE
Descenders get clipped in account selectors

### ISSUE THREAD

**Issue by nguarracino** [spazproject/Spaz-Enyo#82]
My main twitter account is @nguarracino. In the account ListSelector in the compose and search Popups, the descender of the "g" gets clipped.

**Comment by willhoney7** [comment]
Can you post a screenshot?

**Comment by funkatron** [comment]
Screenshots are awesome.

## 

Ed Finkler
http://funkatron.com
@funkatron
AIM: funka7ron / ICQ: 3922133 / XMPP:funkatron@gmail.com

**Comment by nguarracino** [comment]
Boy, you guys are awfully needy ;-)

See how the "g" is clipped at the bottom:
https://skitch.com/nguarracino/fbhcf/descender-clip
