### ISSUE TITLE
Follow Users – handling multiple accounts

### ISSUE THREAD

**Issue by willhoney7** [spazproject/Spaz-Enyo#83]
We need to implement a way to follow and unfollow users that works with multiple accounts.

**Comment by funkatron** [comment]
The multiple accounts thing is the issue. I'm close to having this working for the account that is viewing the user, but it will need some UI love to handle alternate accounts. That could also change what is displayed to the user as well: the state of the follow toggle button is set based on the relationship with a given account.

One possibility would be to change what account the relationship data is viewed as within the UserView panel. Maybe a dropdown that lists all accounts with the matching service. The initial setting would be the account that owns the column that opened the UserView. Changing that would force the relationship data to update.

I'll let you work on the UI; I can wire stuff up once that's in there, I think.

**Comment by willhoney7** [comment]
This should be done: 5ad96fd6a86d36fc5c85. Closing!
