### ISSUE TITLE
Add notification prefs

### ISSUE THREAD

**Issue by funkatron** [spazproject/Spaz-Enyo#86]
What do we notify on?
- New messages (not mentions/dms)
- New mentions
- New direct messages
- New search results

**Comment by funkatron** [comment]
By default, we should only notify on mentions and DMs, I think.

**Comment by willhoney7** [comment]
So is this for when the app is open?

Should we just wait and do this when we get background refreshing going?

**Comment by funkatron** [comment]
When it's open. Will also be used for bg notifications when we get those in.

## 

Ed Finkler
http://funkatron.com
@funkatron
AIM: funka7ron / ICQ: 3922133 / XMPP:funkatron@gmail.com

**Comment by willhoney7** [comment]
Okay, I'll add the prefs and let you add the notifying
