### ISSUE TITLE
Add favoriting of entries

### ISSUE THREAD

**Issue by funkatron** [spazproject/Spaz-Enyo#89]
Needs to go into EntryViewClick and EntryView.

Arbitrarily assigned to Will, but someone else can pick it up.

**Comment by willhoney7** [comment]
Also, whenever a tweet is favorited or unfavorited, it should refresh all 'favorite' columns.

**Comment by funkatron** [comment]
apparently I think josh is will.

**Comment by funkatron** [comment]
as part of this, need to add is_favorite as an attribute of the standard entry format

**Comment by funkatron** [comment]
added is_favorite as entry attribute in c043dc6b87ec8dede8488651d4bc2738a3696cc1

**Comment by willhoney7** [comment]
Okay, done in EntryView: 894c1cd65b64064ab31c

Still need to do it in EntryClickPopup and add a favorite indicator, so keeping this open

**Comment by funkatron** [comment]
in 894c1cd, is the button supposed to be blank/invisible if the entry is not a fav? because that's what i'm seeing here.

**Comment by willhoney7** [comment]
No, it's not. Can I get a screencast/screenshot?

**Comment by funkatron** [comment]
Even better, a video:

http://screencast.com/t/bS2nXS8u

Did you maybe forget to add icon-favorite-outline.png to your repo when you committed?

**Comment by willhoney7** [comment]
Woopsy, pushed the image up: f64165c8a435a6103fd4

**Comment by willhoney7** [comment]
Okay, finished this in b0deb92ab9a6e993b0af. I'm going to add the methods to refresh the timelines once an entry has been favorited, so leaving open for now.
