### ISSUE TITLE
Tweetmarks API

### ISSUE THREAD

**Issue by dcousineau** [spazproject/Spaz-Enyo#94]
http://www.marco.org/2011/06/03/tweetmarks

Might be a cool feature to have

**Comment by funkatron** [comment]
We actually already have that built into our own web APIs – we just haven't done anything with it yet. I'm emailing the dude anyway tho.

## 

Ed Finkler
http://funkatron.com
@funkatron
AIM: funka7ron / ICQ: 3922133 / XMPP:funkatron@gmail.com

**Comment by joshthecoder** [comment]
Sticking with our own web API for "marking" the last read item I think is the best way.
I just don't feel there's enough other clients that support "tweetmarks" to make it worthwhile.
