### ISSUE TITLE
Decide whether to keep "home" timeline and "unified" columns separate.

### ISSUE THREAD

**Issue by willhoney7** [spazproject/Spaz-Enyo#98]
I think it would be better to have the "home" column BE the "unified" column. Many people won't know the difference and they will wonder when adding a column. Every desktop twitter app I've used does not distinguish between them. Keeping them separate doesn't make much sense to me, but I'm open to suggestions. Thoughts?

**Comment by funkatron** [comment]
Merge them. it's fine for now.
