### ISSUE TITLE
Marking entries as "read"

### ISSUE THREAD

**Issue by funkatron** [spazproject/Spaz-Enyo#99]
How do we mark something as read? when do we mark it as read?

How do we persist read state between app runs?

**Comment by funkatron** [comment]
I have implemented marking as read when a column is refreshed. Simple CSS is applied to dim the text of the entry a bit (similar to what happens in the email app). For the moment I think this works, but perhaps more could be done on the UI side to pretty-up things.

last-read id is NOT saved. That will require more logic work.

See f4ec9ce2c1034370883a9fa42985bcc8d37992a5

**Comment by weierophinney** [comment]
Tweetmarks defines last-read as whatever is at the top of the column. If using Tweetmarks, then the question becomes, "when do we notify Tweetmarks?"

**Comment by funkatron** [comment]
Tweetmarks only works with Twitter, so isn't a great option for us (also is closed source and run by one guy; I've seen too many services like that die out and then require me to rewrite stuff to drop it).

We do have a last-read syncing capability in the Spaz Web APIs. I intend to use that when possible. Efforts in that area are encouraged.

## 

Ed Finkler
http://funkatron.com
@funkatron
AIM: funka7ron / ICQ: 3922133 / XMPP:funkatron@gmail.com

**Comment by funkatron** [comment]
I have implemented this locally now -- it saves between sessions. I'll call this closed for the purposes of this milestone.
